/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * botany.java
 *
 * Created on Oct 24, 2014, 10:11:38 PM
 */

package compproject;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mukesh
 */
public class botany extends javax.swing.JFrame {

    /** Creates new form botany */
    public botany() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoomDial = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        plant_pic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        locTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descTA = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        kingdom = new javax.swing.JLabel();
        division = new javax.swing.JLabel();
        cla = new javax.swing.JLabel();
        orderTxt = new javax.swing.JLabel();
        fmlyTxt = new javax.swing.JLabel();
        genusTxt = new javax.swing.JLabel();
        speciesTxt = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        factTA = new javax.swing.JTextArea();
        yrTA = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        mediqTA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchCB = new javax.swing.JComboBox();
        nads = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        pic1_pan = new javax.swing.JPanel();
        pic1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pic2_pan = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();
        outcount = new javax.swing.JLabel();
        slash = new javax.swing.JLabel();
        nowcount = new javax.swing.JLabel();

        zoomDial.setMinimumSize(new java.awt.Dimension(852, 602));

        plant_pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane5.setViewportView(plant_pic);

        javax.swing.GroupLayout zoomDialLayout = new javax.swing.GroupLayout(zoomDial.getContentPane());
        zoomDial.getContentPane().setLayout(zoomDialLayout);
        zoomDialLayout.setHorizontalGroup(
            zoomDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
        zoomDialLayout.setVerticalGroup(
            zoomDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1076, 637));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Botanical Database");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Common Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Scientific Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Description:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Location:");

        locTA.setColumns(20);
        locTA.setEditable(false);
        locTA.setRows(5);
        locTA.setWrapStyleWord(true);
        locTA.setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));
        locTA.setOpaque(false);
        jScrollPane1.setViewportView(locTA);

        descTA.setEditable(false);
        descTA.setRows(5);
        descTA.setToolTipText("Description");
        descTA.setWrapStyleWord(true);
        descTA.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));
        descTA.setOpaque(false);
        jScrollPane2.setViewportView(descTA);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Scientific Data"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel7.setText("Kingdom:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel8.setText("Division:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel9.setText("Order:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel10.setText("Class:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel11.setText("Species:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel12.setText("Family:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel14.setText("Genus:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(fmlyTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speciesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(genusTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(cla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(kingdom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(division, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kingdom, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(cla, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(orderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fmlyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(genusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(speciesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setText("Biological Facts:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel26.setText("Medicinal qualities:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel27.setText("<html>Year of Plantation:<br>(approx.)");

        factTA.setEditable(false);
        factTA.setRows(5);
        factTA.setToolTipText("Biological Facts");
        factTA.setWrapStyleWord(true);
        factTA.setBorder(javax.swing.BorderFactory.createTitledBorder("Biological Facts"));
        factTA.setOpaque(false);
        jScrollPane3.setViewportView(factTA);

        mediqTA.setEditable(false);
        mediqTA.setRows(5);
        mediqTA.setToolTipText("Medicinal Properties");
        mediqTA.setWrapStyleWord(true);
        mediqTA.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicinal Qualities"));
        mediqTA.setOpaque(false);
        jScrollPane4.setViewportView(mediqTA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yrTA, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sname, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(yrTA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 790, 500));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Sort by:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, -1));

        searchTxt.setFont(new java.awt.Font("Tahoma", 1, 14));
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        getContentPane().add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 210, 30));

        searchCB.setFont(new java.awt.Font("Tahoma", 1, 12));
        searchCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Common Name", "Location", "Description" }));
        searchCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCBActionPerformed(evt);
            }
        });
        getContentPane().add(searchCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 130, -1));

        nads.setFont(new java.awt.Font("Tahoma", 1, 14));
        nads.setText("Please enter Common Name:");
        getContentPane().add(nads, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 240, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel32.setText("At School");

        jButton1.setText("Zoom");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pic1_panLayout = new javax.swing.GroupLayout(pic1_pan);
        pic1_pan.setLayout(pic1_panLayout);
        pic1_panLayout.setHorizontalGroup(
            pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pic1_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pic1_panLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addGap(70, 70, 70))
        );
        pic1_panLayout.setVerticalGroup(
            pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pic1_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        getContentPane().add(pic1_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, -1, -1));

        jButton2.setText("Zoom");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel31.setText("Typical Appearance");

        javax.swing.GroupLayout pic2_panLayout = new javax.swing.GroupLayout(pic2_pan);
        pic2_pan.setLayout(pic2_panLayout);
        pic2_panLayout.setHorizontalGroup(
            pic2_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pic2_panLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pic2_panLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addGap(49, 49, 49))
        );
        pic2_panLayout.setVerticalGroup(
            pic2_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pic2_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pic2_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(pic2_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, -1, -1));

        previous.setFont(new java.awt.Font("Tahoma", 1, 12));
        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        getContentPane().add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, -1, -1));

        next.setFont(new java.awt.Font("Tahoma", 1, 12));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, -1));

        outcount.setFont(new java.awt.Font("Tahoma", 1, 14));
        outcount.setText("0");
        getContentPane().add(outcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 30, 30));

        slash.setFont(new java.awt.Font("Tahoma", 1, 14));
        slash.setText("/");
        getContentPane().add(slash, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 10, 30));

        nowcount.setFont(new java.awt.Font("Tahoma", 1, 14));
        nowcount.setText("0");
        getContentPane().add(nowcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 30, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public BufferedImage img1,img2;
    public void smsearch(String genus,String species){
 
            try {

             Class.forName("com.mysql.jdbc.Driver");
             Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
             Statement stmt=(Statement)con.createStatement();

             String sql1="Select * from botany where genus like '"+genus+"' and species like '"+species+"';";
             ResultSet rs=stmt.executeQuery(sql1);

             rs.next();
             String c_name=rs.getString("c_name");
             String king=rs.getString("Kingdom");
             String div=rs.getString("Division");      
             String cls=rs.getString("Class");
             String order=rs.getString("bot_order");
             String family=rs.getString("Family");
             String gen=rs.getString("Genus");
             String spec=rs.getString("Species");

             cname.setText(c_name);
             kingdom.setText(king);
             division.setText(div);
             cla.setText(cls);
             orderTxt.setText(order);
             fmlyTxt.setText(family);
             genusTxt.setText(gen);
             speciesTxt.setText(spec);
             sname.setText(gen+" "+spec);

             
             
             String loc=rs.getString("location");
             String desc=rs.getString("Description");
             String bio_fact=rs.getString("bio_fact");
             String Medi_qual=rs.getString("medi_qual");
             String yr=rs.getString("yr_plant");

             locTA.setText(loc);
             descTA.setText(desc);
             factTA.setText(bio_fact);
             mediqTA.setText(Medi_qual);
             yrTA.setText(yr);

             InputStream in1 = rs.getBinaryStream("pic_skool");
            InputStream in2 = rs.getBinaryStream("pic_out");

            if(in1!=null){
             pic1_pan.setVisible(true);
             img1=ImageIO.read(in1);
             Image toolkit1=img1.getScaledInstance(300,190,Image.SCALE_SMOOTH);
             BufferedImage newImage1=new BufferedImage(300,190,BufferedImage.TYPE_INT_ARGB);
             Graphics g1=newImage1.getGraphics();
             g1.drawImage(toolkit1,0,0,null);
             pic1.setIcon(new ImageIcon(newImage1));
            }
            else{
                pic1_pan.setVisible(false);
            }

            if(in2!=null){
             pic2_pan.setVisible(true);
             img2=ImageIO.read(in2);
             Image toolkit2=img2.getScaledInstance(300,190,Image.SCALE_SMOOTH);
             BufferedImage newImage2=new BufferedImage(300,190,BufferedImage.TYPE_INT_ARGB);
             Graphics g2=newImage2.getGraphics();
             g2.drawImage(toolkit2,0,0,null);
             pic2.setIcon(new ImageIcon(newImage2));
            }
            else{
                pic2_pan.setVisible(false);
            }

            }

            catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
            }

                 }

    private void searchCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCBActionPerformed
        nads.setVisible(true);
        searchTxt.setText("");
        searchTxt.setVisible(true);
        searchTxt.requestFocusInWindow();
        searchBtn.setVisible(true);
        String x=(String) searchCB.getSelectedItem();
        nads.setText("Please enter "+x+" :");
        
}//GEN-LAST:event_searchCBActionPerformed

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        searchBtn.doClick();
}//GEN-LAST:event_searchTxtActionPerformed
public ResultSet rs1,rsc1;
public int count,ncount;
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        previous.setEnabled(false);
        next.setEnabled(true);

        pic1_pan.setVisible(true);
        pic2_pan.setVisible(true);
        jPanel1.setVisible(true);
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
             Statement stm=(Statement)conn.createStatement();

             String x=(String) searchCB.getSelectedItem();
             String nm=searchTxt.getText();

             if(x.equals("Common Name")){

                 String sql2="Select count(*) from botany where c_name like '%"+nm+"';";

                 rsc1=stm.executeQuery(sql2);
                 rsc1.next();
                 count=rsc1.getInt("count(*)");
                 
                 String sql1="Select genus,species from botany where c_name like '%"+nm+"';";

                 rs1=stm.executeQuery(sql1);
                 rs1.next();
                 String gen=rs1.getString("Genus");
                 String spec=rs1.getString("Species");
                 smsearch(gen,spec);
             }
             
             else if(x.equals("Location")){
                 String sql2="Select count(*) from botany where location like '%"+nm+"%';";

                 rsc1=stm.executeQuery(sql2);
                 rsc1.next();
                 count=rsc1.getInt("count(*)");

                 String sql1="Select genus,species from botany where location like '%"+nm+"%';";
                 rs1=stm.executeQuery(sql1);
                 rs1.next();
                 String gen=rs1.getString("Genus");
                 String spec=rs1.getString("Species");
                 smsearch(gen,spec);
             }

             else if(x.equals("Description")){
                  String sql2="Select count(*) from botany where Description like '%"+nm+"%';";

                 rsc1=stm.executeQuery(sql2);
                 rsc1.next();
                 count=rsc1.getInt("count(*)");

                 
                 String sql1="Select genus,species from botany where Description like '%"+nm+"%';";
                 rs1=stm.executeQuery(sql1);
                 rs1.next();
                 String gen=rs1.getString("Genus");
                 String spec=rs1.getString("Species");
                 smsearch(gen,spec);
             }

             if(count==1)
                   next.setEnabled(false);

                ncount=1;
                outcount.setText(""+count);
                nowcount.setText(""+ncount);

                rsc1.close();
             
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
            jPanel1.setVisible(false);
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        zoomDial.show();
        plant_pic.setIcon(new ImageIcon(img1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        zoomDial.show();
        plant_pic.setIcon(new ImageIcon(img2));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        try {
            pic1_pan.setVisible(true);
            pic2_pan.setVisible(true);

            rs1.previous();
            String gen=rs1.getString("genus");
            String spec=rs1.getString("Species");
            smsearch(gen,spec);

            next.setEnabled(true);
            if(ncount==2){
                previous.setEnabled(false);
            }
            

            ncount-=1;
            nowcount.setText(""+ncount);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        try {
            pic1_pan.setVisible(true);
            pic2_pan.setVisible(true);
            
            previous.setEnabled(true);

            if(count-ncount==1){
            next.setEnabled(false);
            }
            
            rs1.next();
            String gen=rs1.getString("genus");
            String spec=rs1.getString("Species");
            System.out.println(gen+" "+spec);
            smsearch(gen,spec);
            
            ncount+=1;
            nowcount.setText(""+ncount);

        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_nextActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new botany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cla;
    private javax.swing.JLabel cname;
    private javax.swing.JTextArea descTA;
    private javax.swing.JLabel division;
    private javax.swing.JTextArea factTA;
    private javax.swing.JLabel fmlyTxt;
    private javax.swing.JLabel genusTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel kingdom;
    private javax.swing.JTextArea locTA;
    private javax.swing.JTextArea mediqTA;
    private javax.swing.JLabel nads;
    private javax.swing.JButton next;
    private javax.swing.JLabel nowcount;
    private javax.swing.JLabel orderTxt;
    private javax.swing.JLabel outcount;
    private javax.swing.JLabel pic1;
    private javax.swing.JPanel pic1_pan;
    private javax.swing.JLabel pic2;
    private javax.swing.JPanel pic2_pan;
    private javax.swing.JLabel plant_pic;
    private javax.swing.JButton previous;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox searchCB;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel slash;
    private javax.swing.JLabel sname;
    private javax.swing.JLabel speciesTxt;
    private javax.swing.JLabel yrTA;
    private javax.swing.JDialog zoomDial;
    // End of variables declaration//GEN-END:variables

}
