/*
 * To change this template, choose Tools | Templates
 * and open the template in the ediSStor.
 */

/*
 * botany_insert.java
 *
 * Created on Oct 29, 2014, 7:46:40 PM
 */

package compproject;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Mukesh
 */
public class botany_insert extends javax.swing.JFrame {

    /** Creates new form botany_insert */
    public botany_insert() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_skool = new javax.swing.JDialog();
        fc_skool = new javax.swing.JFileChooser();
        Dialog_out = new javax.swing.JDialog();
        fc_out = new javax.swing.JFileChooser();
        zoomDial = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        plant_pic = new javax.swing.JLabel();
        yrTA = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c_nameTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        locTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descTA = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        factTA = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        mediqTA = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        yrCB = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        divTxt = new javax.swing.JTextField();
        clsTxt = new javax.swing.JTextField();
        ordTxt = new javax.swing.JTextField();
        fmlyTxt = new javax.swing.JTextField();
        genusTxt = new javax.swing.JTextField();
        specTxt = new javax.swing.JTextField();
        kingdomCB = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        upsklBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        upoutBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pic1_pan = new javax.swing.JPanel();
        pic1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        zoom_skool = new javax.swing.JButton();
        pic2_pan = new javax.swing.JPanel();
        zoom_out = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        fc_skool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc_skoolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_skoolLayout = new javax.swing.GroupLayout(Dialog_skool.getContentPane());
        Dialog_skool.getContentPane().setLayout(Dialog_skoolLayout);
        Dialog_skoolLayout.setHorizontalGroup(
            Dialog_skoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fc_skool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Dialog_skoolLayout.setVerticalGroup(
            Dialog_skoolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fc_skool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        fc_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fc_outActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Dialog_outLayout = new javax.swing.GroupLayout(Dialog_out.getContentPane());
        Dialog_out.getContentPane().setLayout(Dialog_outLayout);
        Dialog_outLayout.setHorizontalGroup(
            Dialog_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fc_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Dialog_outLayout.setVerticalGroup(
            Dialog_outLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fc_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        zoomDial.setMinimumSize(new java.awt.Dimension(852, 602));

        plant_pic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane5.setViewportView(plant_pic);

        javax.swing.GroupLayout zoomDialLayout = new javax.swing.GroupLayout(zoomDial.getContentPane());
        zoomDial.getContentPane().setLayout(zoomDialLayout);
        zoomDialLayout.setHorizontalGroup(
            zoomDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
        );
        zoomDialLayout.setVerticalGroup(
            zoomDialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(929, 680));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(yrTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Common Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Location:");

        locTA.setColumns(20);
        locTA.setRows(5);
        locTA.setWrapStyleWord(true);
        locTA.setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));
        jScrollPane1.setViewportView(locTA);

        descTA.setRows(5);
        descTA.setToolTipText("Description");
        descTA.setWrapStyleWord(true);
        descTA.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));
        jScrollPane2.setViewportView(descTA);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Description:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel25.setText("Biological Facts:");

        factTA.setRows(5);
        factTA.setToolTipText("Biological Facts");
        factTA.setWrapStyleWord(true);
        factTA.setBorder(javax.swing.BorderFactory.createTitledBorder("Biological Facts"));
        jScrollPane3.setViewportView(factTA);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel26.setText("Medicinal qualities:");

        mediqTA.setRows(5);
        mediqTA.setToolTipText("Medicinal Properties");
        mediqTA.setWrapStyleWord(true);
        mediqTA.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicinal Qualities"));
        jScrollPane4.setViewportView(mediqTA);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel27.setText("<html>Year of Plantation:<br>(approx.)");

        yrCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1998", "1999", "2000", "2001" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(70, 70, 70)
                            .addComponent(c_nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(69, 69, 69)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(92, 92, 92)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(108, 108, 108)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addGap(50, 50, 50)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(yrCB, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))))
                .addGap(213, 213, 213))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(yrCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel1);

        jLabel12.setFont(new java.awt.Font("Aharoni", 1, 16));
        jLabel12.setText("Family:");

        jLabel14.setFont(new java.awt.Font("Aharoni", 1, 16));
        jLabel14.setText("Genus:");

        jLabel11.setFont(new java.awt.Font("Aharoni", 1, 16));
        jLabel11.setText("Species:");

        jLabel7.setFont(new java.awt.Font("Aharoni", 1, 16));
        jLabel7.setText("Kingdom:");

        jLabel8.setFont(new java.awt.Font("Aharoni", 1, 16));
        jLabel8.setText("Division:");

        jLabel10.setFont(new java.awt.Font("Aharoni", 1, 16));
        jLabel10.setText("Class:");

        jLabel9.setFont(new java.awt.Font("Aharoni", 1, 16));
        jLabel9.setText("Order:");

        kingdomCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plantae", "Monera", "Protista", "Fungi", "Animalia" }));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14));
        jLabel4.setText("* Note: Scientific Name is the combination of Genus and Species names.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(specTxt)
                    .addComponent(divTxt)
                    .addComponent(clsTxt)
                    .addComponent(kingdomCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fmlyTxt)
                    .addComponent(ordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(genusTxt))
                .addGap(276, 276, 276))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kingdomCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(clsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fmlyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(genusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(specTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Scientific Data", jPanel2);

        upsklBtn.setText("Upload Photo");
        upsklBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upsklBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16));
        jLabel1.setText("Upload Photo of Plant inside school");

        upoutBtn.setText("Upload Photo");
        upoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upoutBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 16));
        jLabel3.setText("<html><center>Upload Photo of Typical Appearance<br>of Plant anywhere outside</center>");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel32.setText("At School");

        zoom_skool.setText("Zoom");
        zoom_skool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoom_skoolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pic1_panLayout = new javax.swing.GroupLayout(pic1_pan);
        pic1_pan.setLayout(pic1_panLayout);
        pic1_panLayout.setHorizontalGroup(
            pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pic1_panLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pic1_panLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(20, 20, 20)
                .addComponent(zoom_skool)
                .addGap(70, 70, 70))
        );
        pic1_panLayout.setVerticalGroup(
            pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pic1_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pic1_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(zoom_skool))
                .addContainerGap())
        );

        zoom_out.setText("Zoom");
        zoom_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoom_outActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel31.setText("Typical Appearance");

        javax.swing.GroupLayout pic2_panLayout = new javax.swing.GroupLayout(pic2_pan);
        pic2_pan.setLayout(pic2_panLayout);
        pic2_panLayout.setHorizontalGroup(
            pic2_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pic2_panLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pic2_panLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(13, 13, 13)
                .addComponent(zoom_out)
                .addGap(49, 49, 49))
        );
        pic2_panLayout.setVerticalGroup(
            pic2_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pic2_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pic2_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(zoom_out))
                .addContainerGap())
        );

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton5.setText("Save to Database");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(57, 57, 57))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upoutBtn)
                            .addComponent(upsklBtn)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic1_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pic2_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(510, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(upsklBtn))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upoutBtn)
                    .addComponent(jLabel3))
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pic1_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pic2_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(25, 25, 25))))
        );

        jTabbedPane1.addTab("Upload Photos", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zoom_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoom_outActionPerformed
    zoomDial.show();
        plant_pic.setIcon(new ImageIcon(img2));
}//GEN-LAST:event_zoom_outActionPerformed

    private void zoom_skoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoom_skoolActionPerformed
        zoomDial.show();
        plant_pic.setIcon(new ImageIcon(img1));
}//GEN-LAST:event_zoom_skoolActionPerformed
    public BufferedImage img1=null,img2=null;
    public File out=null,skool=null;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pic1_pan.setVisible(false);
        pic2_pan.setVisible(false);

        FileNameExtensionFilter filter=new FileNameExtensionFilter("Images and Photots","jpg");

        fc_skool.setFileFilter(filter);
        fc_skool.setAcceptAllFileFilterUsed(false);

        fc_out.setFileFilter(filter);
        fc_out.setAcceptAllFileFilterUsed(false);
    }//GEN-LAST:event_formWindowOpened

    private void upsklBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upsklBtnActionPerformed
    int state=fc_skool.showOpenDialog(null);
}//GEN-LAST:event_upsklBtnActionPerformed

    private void upoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upoutBtnActionPerformed
    int state=fc_out.showOpenDialog(null);
}//GEN-LAST:event_upoutBtnActionPerformed

    private void fc_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc_outActionPerformed
        out=fc_out.getSelectedFile();
        try {
            pic2_pan.setVisible(true);
            
            img2 = ImageIO.read(out);
            Image toolkit2=img2.getScaledInstance(300,190,Image.SCALE_SMOOTH);
            BufferedImage newImage2=new BufferedImage(300,190,BufferedImage.TYPE_INT_ARGB);
            Graphics g2=newImage2.getGraphics();
            g2.drawImage(toolkit2,0,0,null);
            pic2.setIcon(new ImageIcon(newImage2));
             
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_fc_outActionPerformed

    private void fc_skoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fc_skoolActionPerformed
        skool=fc_skool.getSelectedFile();
        try {
            pic1_pan.setVisible(true);

            img1 = ImageIO.read(skool);
            Image toolkit1=img1.getScaledInstance(300,190,Image.SCALE_SMOOTH);
            BufferedImage newImage1=new BufferedImage(300,190,BufferedImage.TYPE_INT_ARGB);
            Graphics g1=newImage1.getGraphics();
            g1.drawImage(toolkit1,0,0,null);
            pic1.setIcon(new ImageIcon(newImage1));

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_fc_skoolActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");

            String c_nm=c_nameTxt.getText();
            
            String loc=null;
            if(locTA.getText().length()!=0)
                loc=locTA.getText();
            
            String des=null;
            if(descTA.getText().length()!=0)
                des=descTA.getText();
            
            String fc=null;
            if(factTA.getText().length()!=0)
                fc=factTA.getText();

            String mq=null;
            if(mediqTA.getText().length()!=0)
                mq=mediqTA.getText();

            String yr=(String) yrCB.getSelectedItem();

            String kingdom=(String) kingdomCB.getSelectedItem();
            String div= divTxt.getText();

            String cls=null;
                if(clsTxt.getText().length()!=0)
                    cls=clsTxt.getText();
            
            String ord=null;
                if(ordTxt.getText().length()!=0)
                    ord=ordTxt.getText();

            String fmly=null;
            if(fmlyTxt.getText().length()!=0)
                    fmly=fmlyTxt.getText();
            
            String genus=genusTxt.getText();
            String spec=specTxt.getText();

           FileInputStream  fis1=null;
           int l1=0;
           if(skool!=null){
           fis1 = new FileInputStream(skool);
           l1=(int) (skool.length());
           }

           FileInputStream  fis2=null ;
           int l2=0;
           if(out!=null){
           fis2 = new FileInputStream(out);
           l2=(int) (out.length());
           }
           
          String query = " insert into botany values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
          PreparedStatement preparedStmt = con.prepareStatement(query);

          preparedStmt.setString(1, c_nm);
          preparedStmt.setString(2, kingdom);
          preparedStmt.setString(3, div);
          preparedStmt.setString(4, cls);
          preparedStmt.setString(5, ord);
          preparedStmt.setString(6, fmly);
          preparedStmt.setString(7, genus);
          preparedStmt.setString(8, spec);
          preparedStmt.setString(9,loc);
          preparedStmt.setString(10, des);
          preparedStmt.setString(11, fc);
          preparedStmt.setString(12, mq);
          preparedStmt.setString(13, yr);

           preparedStmt.setBinaryStream(14,fis1,l1);
           preparedStmt.setBinaryStream(15,fis2,l2);

           preparedStmt.execute();
           con.close();
           JOptionPane.showMessageDialog(null,"Record Successfully added");
        }
        catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new botany_insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Dialog_out;
    private javax.swing.JDialog Dialog_skool;
    private javax.swing.JTextField c_nameTxt;
    private javax.swing.JTextField clsTxt;
    private javax.swing.JTextArea descTA;
    private javax.swing.JTextField divTxt;
    private javax.swing.JTextArea factTA;
    private javax.swing.JFileChooser fc_out;
    private javax.swing.JFileChooser fc_skool;
    private javax.swing.JTextField fmlyTxt;
    private javax.swing.JTextField genusTxt;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox kingdomCB;
    private javax.swing.JTextArea locTA;
    private javax.swing.JTextArea mediqTA;
    private javax.swing.JTextField ordTxt;
    private javax.swing.JLabel pic1;
    private javax.swing.JPanel pic1_pan;
    private javax.swing.JLabel pic2;
    private javax.swing.JPanel pic2_pan;
    private javax.swing.JLabel plant_pic;
    private javax.swing.JLabel sname;
    private javax.swing.JTextField specTxt;
    private javax.swing.JButton upoutBtn;
    private javax.swing.JButton upsklBtn;
    private javax.swing.JComboBox yrCB;
    private javax.swing.JLabel yrTA;
    private javax.swing.JDialog zoomDial;
    private javax.swing.JButton zoom_out;
    private javax.swing.JButton zoom_skool;
    // End of variables declaration//GEN-END:variables

}
