/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Exam_parameter.java
 *
 * Created on Oct 21, 2014, 2:41:50 PM
 */

package compproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Mukesh
 */
public class Exam_parameter extends javax.swing.JFrame {

    /** Creates new form Exam_parameter */
    public Exam_parameter() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        secLbl = new javax.swing.JLabel();
        clsCB = new javax.swing.JComboBox();
        secCB = new javax.swing.JComboBox();
        semLbl = new javax.swing.JLabel();
        semCB = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        P4 = new javax.swing.JPanel();
        P4conLbl = new javax.swing.JLabel();
        Para4CB = new javax.swing.JComboBox();
        convertP4 = new javax.swing.JTextField();
        P4curLbl = new javax.swing.JLabel();
        curP4 = new javax.swing.JTextField();
        Para2Lbl = new javax.swing.JLabel();
        P1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Para1CB = new javax.swing.JComboBox();
        convertP1 = new javax.swing.JTextField();
        P1curLbl = new javax.swing.JLabel();
        curP1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        P2 = new javax.swing.JPanel();
        P2conLbl = new javax.swing.JLabel();
        Para2CB = new javax.swing.JComboBox();
        convertP2 = new javax.swing.JTextField();
        P2curLbl = new javax.swing.JLabel();
        curP2 = new javax.swing.JTextField();
        Para2Lbl1 = new javax.swing.JLabel();
        P3 = new javax.swing.JPanel();
        P3conLbl = new javax.swing.JLabel();
        Para3CB = new javax.swing.JComboBox();
        convertP3 = new javax.swing.JTextField();
        P3curLbl = new javax.swing.JLabel();
        curP3 = new javax.swing.JTextField();
        Para2Lbl2 = new javax.swing.JLabel();
        LblMark100 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        entBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        subLbl = new javax.swing.JLabel();
        subCB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1046, 543));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18));
        jLabel1.setText("Exam Parameter Definition");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 1, 14));
        jLabel2.setText("Class:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        secLbl.setFont(new java.awt.Font("Eras Demi ITC", 1, 14));
        secLbl.setText("Section:");
        getContentPane().add(secLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        clsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsCBActionPerformed(evt);
            }
        });
        getContentPane().add(clsCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 100, 20));

        secCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secCBActionPerformed(evt);
            }
        });
        getContentPane().add(secCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 80, 20));

        semLbl.setFont(new java.awt.Font("Eras Demi ITC", 1, 14));
        semLbl.setText("Semester:");
        getContentPane().add(semLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        semCB.setFont(new java.awt.Font("Tahoma", 1, 11));
        semCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semCBActionPerformed(evt);
            }
        });
        getContentPane().add(semCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 90, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P4conLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        P4conLbl.setText("Convert to Out of:");
        P4.add(P4conLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        Para4CB.setEditable(true);
        Para4CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NULL", "Exam", "Notebook", "Project", "Assignment", "Reading", "Writing", "Speaking", "Listening", "Discipline", "Class test", "Practicals", "Activity" }));
        Para4CB.setNextFocusableComponent(convertP4);
        Para4CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Para4CBActionPerformed(evt);
            }
        });
        P4.add(Para4CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 140, -1));

        convertP4.setNextFocusableComponent(curP4);
        P4.add(convertP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 90, 30));

        P4curLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        P4curLbl.setText("Currently entering out of:");
        P4.add(P4curLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        curP4.setNextFocusableComponent(update);
        P4.add(curP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 80, 30));

        Para2Lbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        Para2Lbl.setText("Parameter 4:");
        P4.add(Para2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 870, 30));

        P1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        jLabel4.setText("Convert to Out of:");
        P1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        Para1CB.setEditable(true);
        Para1CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Exam", "Notebook", "Project", "Assignment" }));
        Para1CB.setNextFocusableComponent(convertP1);
        Para1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Para1CBActionPerformed(evt);
            }
        });
        P1.add(Para1CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 140, -1));

        convertP1.setNextFocusableComponent(curP1);
        P1.add(convertP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 90, 30));

        P1curLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        P1curLbl.setText("Currently entering out of:");
        P1.add(P1curLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        curP1.setNextFocusableComponent(Para2CB);
        P1.add(curP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 80, 30));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        jLabel10.setText("Parameter 1:");
        P1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel1.add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 870, 30));

        P2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P2conLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        P2conLbl.setText("Convert to Out of:");
        P2.add(P2conLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        Para2CB.setEditable(true);
        Para2CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NULL", "Exam", "Notebook", "Project", "Assignment", "Reading", "Writing", "Speaking", "Listening", "Discipline", "Class test", "Practicals", "Activity" }));
        Para2CB.setNextFocusableComponent(curP2);
        Para2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Para2CBActionPerformed(evt);
            }
        });
        P2.add(Para2CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 140, -1));

        convertP2.setNextFocusableComponent(curP2);
        P2.add(convertP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 90, 30));

        P2curLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        P2curLbl.setText("Currently entering out of:");
        P2.add(P2curLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        curP2.setNextFocusableComponent(Para3CB);
        P2.add(curP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 80, 30));

        Para2Lbl1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        Para2Lbl1.setText("Parameter 2:");
        P2.add(Para2Lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 870, 30));

        P3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P3conLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        P3conLbl.setText("Convert to Out of:");
        P3.add(P3conLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        Para3CB.setEditable(true);
        Para3CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NULL", "Exam", "Notebook", "Project", "Assignment", "Reading", "Writing", "Speaking", "Listening", "Discipline", "Class test", "Practicals", "Activity" }));
        Para3CB.setNextFocusableComponent(convertP3);
        Para3CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Para3CBActionPerformed(evt);
            }
        });
        P3.add(Para3CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 140, -1));

        convertP3.setNextFocusableComponent(curP3);
        P3.add(convertP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 90, 30));

        P3curLbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        P3curLbl.setText("Currently entering out of:");
        P3.add(P3curLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        curP3.setNextFocusableComponent(Para4CB);
        P3.add(curP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 80, 30));

        Para2Lbl2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        Para2Lbl2.setText("Parameter 3:");
        P3.add(Para2Lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 870, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 910, 260));

        LblMark100.setFont(new java.awt.Font("Cooper Black", 0, 14));
        LblMark100.setText("* Please ensure the total marks is out of 100");
        getContentPane().add(LblMark100, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        update.setFont(new java.awt.Font("Tahoma", 1, 11));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        entBtn.setText("Enter");
        entBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entBtnActionPerformed(evt);
            }
        });
        getContentPane().add(entBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        jLabel11.setText("Parameter 1:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("eg.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16));
        jLabel14.setText("90");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16));
        jLabel12.setText("25");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        jLabel15.setText("Currently entering out of:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 16));
        jLabel5.setText("Exam");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15));
        jLabel13.setText("Convert to Out of:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 850, 30));

        subLbl.setFont(new java.awt.Font("Eras Demi ITC", 1, 14));
        subLbl.setText("Subject:");
        getContentPane().add(subLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        subCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCBActionPerformed(evt);
            }
        });
        getContentPane().add(subCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String t_code;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        secCB.setVisible(false);
        secLbl.setVisible(false);
        semCB.setVisible(false);
        semLbl.setVisible(false);
        subCB.setVisible(false);
        subLbl.setVisible(false);

        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        update.setVisible(false);
        LblMark100.setVisible(false);
        
        t_code=JOptionPane.showInputDialog(null,"Please enter teacher code");

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();

            String sql1="Select distinct(class) from subjects where tch_code like '"+t_code+"';";
            ResultSet rs1=stmt.executeQuery(sql1);
            while(rs1.next()){
                int c=rs1.getInt("class");
                clsCB.addItem(c);
            }

            con.close();
            stmt.close();
            rs1.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }
        
    }//GEN-LAST:event_formWindowOpened
public int cl;
public String sc,sem,sub;
    private void clsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsCBActionPerformed
        secCB.setVisible(true);
        secLbl.setVisible(true);
        semCB.setVisible(true);
        semLbl.setVisible(true);
        subCB.setVisible(true);
        subLbl.setVisible(true);

        try {
            JComboBox cla = (JComboBox) evt.getSource();
            cl = (Integer) cla.getSelectedItem();
            System.out.println(""+cl);

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();
            
            String sql2="Select distinct(section) from subjects where tch_code like '"+t_code+"' and class="+cl+";";
            ResultSet rs2 = stmt.executeQuery(sql2);

            int cnt_sec=secCB.getItemCount();
            if(cnt_sec!=0){
                while(cnt_sec!=0){
                secCB.removeItemAt(0);
                cnt_sec=secCB.getItemCount();
                }
            }
            
            while(rs2.next()){
                String s=rs2.getString("Section");
                secCB.addItem(s);
            }

            String sql3="select distinct(semester) from semesters where class="+cl+";";
            ResultSet rs3=stmt.executeQuery(sql3);

            int cnt_sem=semCB.getItemCount();
            if(cnt_sem!=0){
                while(cnt_sem!=0){
                semCB.removeItemAt(0);
                cnt_sem=semCB.getItemCount();
                }
            }
            while(rs3.next()){
                String se=rs3.getString("Semester");
                semCB.addItem(se);
            }
            
            con.close();
            stmt.close();
            rs2.close();
            rs3.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
}//GEN-LAST:event_clsCBActionPerformed

    private void Para4CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Para4CBActionPerformed

}//GEN-LAST:event_Para4CBActionPerformed

    private void Para1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Para1CBActionPerformed
        Para4CB.setVisible(true);
    }//GEN-LAST:event_Para1CBActionPerformed

    private void entBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entBtnActionPerformed
        jPanel2.setVisible(true);
        jPanel1.setVisible(true);
        LblMark100.setVisible(true);
        update.setVisible(true);

        P3.setVisible(false);
        P4.setVisible(false);

        Para1CB.requestFocus();
}//GEN-LAST:event_entBtnActionPerformed

    private void Para2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Para2CBActionPerformed
       String p=(String) Para2CB.getSelectedItem();
       if(p.equals("NULL")){
           P3.setVisible(false);
           P4.setVisible(false);
       }
       else{
           P3.setVisible(true);
       }
}//GEN-LAST:event_Para2CBActionPerformed

    private void Para3CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Para3CBActionPerformed
        String p=(String) Para3CB.getSelectedItem();
        
       if(p.equals("NULL")){
           P4.setVisible(false);
       }
       else{
           P4.setVisible(true);
       }
}//GEN-LAST:event_Para3CBActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
       try{
       
       String para_1=(String) Para1CB.getSelectedItem();

       int para_1con=Integer.parseInt(convertP1.getText());
       int para_1cur=Integer.parseInt(curP1.getText());

       String para_2=(String) Para2CB.getSelectedItem();
       int para_2con=0;
       int para_2cur=0;
       
       if(para_2.equals("NULL"))
           para_2=null;

       else{
           para_2con=Integer.parseInt(convertP2.getText());
           para_2cur=Integer.parseInt(curP2.getText());
       }

       String para_3=(String) Para3CB.getSelectedItem();
       int para_3con=0;
       int para_3cur=0;

       if(para_3.equals("NULL"))
           para_3=null;

       else{
          para_3con=Integer.parseInt(convertP3.getText());
          para_3cur=Integer.parseInt(curP3.getText());
       }
       
       String para_4=(String) Para4CB.getSelectedItem();
       int para_4con=0;
       int para_4cur=0;
       
       if(para_4.equals("NULL"))
           para_4=null;

       else{
          para_4con=Integer.parseInt(convertP4.getText());
          para_4cur=Integer.parseInt(curP4.getText());
       }
       
       System.out.println(para_1+" "+para_2+" "+para_3+" "+para_4);
       System.out.println(""+para_1con+" "+para_1cur+" "+para_2con+" "+para_2cur+" "+para_3con+" "+para_3cur+" "+para_4con+" "+para_4cur);

       Class.forName("com.mysql.jdbc.Driver");
       Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
       Statement stmt=(Statement)con.createStatement();

       String query = "insert into exam_para values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
       PreparedStatement preparedStmt = con.prepareStatement(query);

       preparedStmt.setString(1,sem);
       preparedStmt.setInt(2,cl);
       preparedStmt.setString(3,sc);
       preparedStmt.setString(4,sub);
       preparedStmt.setString(5,para_1);
       preparedStmt.setInt(6,para_1con);
       preparedStmt.setInt(7,para_1cur);
       preparedStmt.setString(8,para_2);
       preparedStmt.setInt(9,para_2con);
       preparedStmt.setInt(10,para_2cur);
       preparedStmt.setString(11,para_3);
       preparedStmt.setInt(12,para_3con);
       preparedStmt.setInt(13,para_3cur);
       preparedStmt.setString(14,para_4);
       preparedStmt.setInt(15,para_4con);
       preparedStmt.setInt(16,para_4cur);

       //JOptionPane.showConfirmDialog(null,"Please confirm the parameters entered for "+cl+" "+sc+" "+sem+" for "+sub);
       preparedStmt.execute();
       con.close();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
       }


    }//GEN-LAST:event_updateActionPerformed

    private void secCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secCBActionPerformed
try {
            JComboBox sec = (JComboBox) evt.getSource();
            sc=(String) sec.getSelectedItem();
            System.out.println(""+sc);

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();

            String sql="Select subject from subjects where (tch_code='"+t_code+"') and (class="+cl+") and (section='"+sc+"');";
            ResultSet rs = stmt.executeQuery(sql);

            int cnt_sub=subCB.getItemCount();
            System.out.println(cnt_sub);

            if(cnt_sub!=0){
                while(cnt_sub!=0){
                subCB.removeItemAt(0);
                cnt_sub=subCB.getItemCount();
                }
            }

            while(rs.next()){
                String s=rs.getString(1);
                subCB.addItem(s);
            }

            


            con.close();
            stmt.close();
            rs.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_secCBActionPerformed

    private void semCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semCBActionPerformed
       sem=(String) semCB.getSelectedItem();
    }//GEN-LAST:event_semCBActionPerformed

    private void subCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCBActionPerformed
        sub=(String) subCB.getSelectedItem();
    }//GEN-LAST:event_subCBActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam_parameter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblMark100;
    private javax.swing.JPanel P1;
    private javax.swing.JLabel P1curLbl;
    private javax.swing.JPanel P2;
    private javax.swing.JLabel P2conLbl;
    private javax.swing.JLabel P2curLbl;
    private javax.swing.JPanel P3;
    private javax.swing.JLabel P3conLbl;
    private javax.swing.JLabel P3curLbl;
    private javax.swing.JPanel P4;
    private javax.swing.JLabel P4conLbl;
    private javax.swing.JLabel P4curLbl;
    private javax.swing.JComboBox Para1CB;
    private javax.swing.JComboBox Para2CB;
    private javax.swing.JLabel Para2Lbl;
    private javax.swing.JLabel Para2Lbl1;
    private javax.swing.JLabel Para2Lbl2;
    private javax.swing.JComboBox Para3CB;
    private javax.swing.JComboBox Para4CB;
    private javax.swing.JComboBox clsCB;
    private javax.swing.JTextField convertP1;
    private javax.swing.JTextField convertP2;
    private javax.swing.JTextField convertP3;
    private javax.swing.JTextField convertP4;
    private javax.swing.JTextField curP1;
    private javax.swing.JTextField curP2;
    private javax.swing.JTextField curP3;
    private javax.swing.JTextField curP4;
    private javax.swing.JButton entBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox secCB;
    private javax.swing.JLabel secLbl;
    private javax.swing.JComboBox semCB;
    private javax.swing.JLabel semLbl;
    private javax.swing.JComboBox subCB;
    private javax.swing.JLabel subLbl;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
