/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fetchTable.java
 *
 * Created on Oct 20, 2014, 9:18:17 PM
 */

package compproject;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Mukesh
 */
public class fetchTable extends javax.swing.JFrame {

    /** Creates new form fetchTable */
    public fetchTable() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldList = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cls = new javax.swing.JComboBox();
        sec = new javax.swing.JComboBox();
        gender = new javax.swing.JComboBox();
        house = new javax.swing.JComboBox();
        hostel = new javax.swing.JComboBox();
        floor = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        admn = new javax.swing.JRadioButton();
        cl = new javax.swing.JRadioButton();
        nm = new javax.swing.JRadioButton();
        ag = new javax.swing.JRadioButton();
        hl = new javax.swing.JRadioButton();
        he = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        ascRB = new javax.swing.JRadioButton();
        descRB = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        student = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        count = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fields for Display"));
        jPanel1.setFont(new java.awt.Font("Aharoni", 1, 14));

        fieldList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "AdmnNo", "Name", "Class, Section", "DOB", "Sex", "Hostel, Floor", "House" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(fieldList);

        jLabel7.setText("* Please select fields for Display");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jLabel1.setText("Class:");

        jLabel2.setText("Section:");

        jLabel3.setText("Gender:");

        jLabel4.setText("House:");

        jLabel5.setText("Hostel:");

        jLabel6.setText("Floor:");

        cls.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        sec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        house.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        hostel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        floor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hostel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(21, 21, 21)
                            .addComponent(cls, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(sec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(house, 0, 75, Short.MAX_VALUE)
                            .addComponent(floor, 0, 75, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(house, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hostel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 330, 190));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorting"));

        buttonGroup1.add(admn);
        admn.setText("AdmnNo");

        buttonGroup1.add(cl);
        cl.setText("Class");

        buttonGroup1.add(nm);
        nm.setText("Name");

        buttonGroup1.add(ag);
        ag.setText("DOB");

        buttonGroup1.add(hl);
        hl.setText("Hostel");

        buttonGroup1.add(he);
        he.setText("House");

        buttonGroup2.add(ascRB);
        ascRB.setText("Ascending");

        buttonGroup2.add(descRB);
        descRB.setText("Descending");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admn)
                    .addComponent(cl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hl)
                        .addGap(30, 30, 30)
                        .addComponent(he)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(nm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(ag)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ascRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(descRB)
                .addGap(33, 33, 33))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admn)
                    .addComponent(nm)
                    .addComponent(ag))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl)
                    .addComponent(hl)
                    .addComponent(he))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ascRB)
                    .addComponent(descRB))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 270, 150));

        student.setBackground(new java.awt.Color(51, 0, 51));
        student.setFont(new java.awt.Font("Arial Black", 0, 12));
        student.setForeground(new java.awt.Color(255, 255, 255));
        student.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AdmnNo", "Name", "Class", "DOB", "Gender", "Hostel", "House"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student.setRowHeight(25);
        jScrollPane2.setViewportView(student);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 850, 270));

        jButton1.setText("Fetch Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        count.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        count.setText("Showing 0 Results");
        getContentPane().add(count, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();

            String sql1="select distinct(class) from classes order by class;";
            ResultSet rs1=stmt.executeQuery(sql1);

            while(rs1.next()){
                String c=rs1.getString("class");
                cls.addItem(c);
            }

            String sql2="select distinct(section) from classes order by section;";
            ResultSet rs2=stmt.executeQuery(sql2);
            
            while(rs2.next()){
                String s=rs2.getString("section");
                sec.addItem(s);
            }

            String sql3="select distinct(sex) from student_master order by sex;";
            ResultSet rs3=stmt.executeQuery(sql3);

            while(rs3.next()){
                String g=rs3.getString("sex");
                gender.addItem(g);
            }

            String sql4="select distinct(house) from student_master order by house;";
            ResultSet rs4=stmt.executeQuery(sql4);

            while(rs4.next()){
                String h=rs4.getString("house");
                house.addItem(h);
            }

            String sql5="Select distinct(hostel) from hostels order by hostel;";
            ResultSet rs5=stmt.executeQuery(sql5);

            while(rs5.next()){
                String hos=rs5.getString("hostel");
                hostel.addItem(hos);
            }

            String sql6="Select distinct(floor) from hostels order by floor;";
            ResultSet rs6=stmt.executeQuery(sql6);

            while(rs6.next()){
                String f=rs6.getString("floor");
                floor.addItem(f);
            }

            TableColumnModel tcm1 = student.getColumnModel();
             tcm1.getColumn(0).setMaxWidth(75);
             tcm1.getColumn(0).setMinWidth(75);
             tcm1.getColumn(1).setMaxWidth(255);
             tcm1.getColumn(1).setMinWidth(255);
             tcm1.getColumn(2).setMaxWidth(100);
             tcm1.getColumn(2).setMinWidth(100);
             tcm1.getColumn(3).setMaxWidth(110);
             tcm1.getColumn(3).setMinWidth(110);
             tcm1.getColumn(4).setMaxWidth(87);
             tcm1.getColumn(4).setMinWidth(87);
             tcm1.getColumn(5).setMaxWidth(100);
             tcm1.getColumn(5).setMinWidth(100);
             tcm1.getColumn(6).setMaxWidth(108);
             tcm1.getColumn(6).setMinWidth(108);

             DefaultTableCellRenderer centreRenderer = new DefaultTableCellRenderer();
             centreRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
             student.getColumn("AdmnNo").setCellRenderer( centreRenderer );
             student.getColumn("Name").setCellRenderer( centreRenderer );
             student.getColumn("Class").setCellRenderer( centreRenderer );
             student.getColumn("DOB").setCellRenderer( centreRenderer );
             student.getColumn("Gender").setCellRenderer( centreRenderer );
             student.getColumn("Hostel").setCellRenderer( centreRenderer );
             student.getColumn("House").setCellRenderer( centreRenderer );
             
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }

    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //assembling the query string
        Object fld1[]=fieldList.getSelectedValues();
        int len=fld1.length;

        if(len==0){
            fieldList.setSelectionInterval(0, 6);
            len=7;
        }
        System.out.println(""+len);
        
        Object fld[]=fieldList.getSelectedValues();
        
        String qry="SELECT ";
        int i;
        String field=(String) fld[0];
        qry=qry+field;
        for(i=1;i<len;++i){
            String field1=(String) fld[i];
            qry=qry+","+field1;
        }

        qry=qry+" FROM student_master";
        String filter_cl,filter_sec,filter_g,filter_he,filter_hl,filter_f;
        
        filter_cl=(String) cls.getSelectedItem();
        filter_sec=(String) sec.getSelectedItem();
        filter_g=(String) gender.getSelectedItem();
        filter_he=(String) house.getSelectedItem();
        filter_hl=(String) hostel.getSelectedItem();
        filter_f=(String) floor.getSelectedItem();

        if(filter_cl.equals("ANY"))
            filter_cl="%";
        if(filter_sec.equals("ANY"))
            filter_sec="%";
        if(filter_g.equals("ANY"))
            filter_g="%";
        if(filter_he.equals("ANY"))
            filter_he="%";
        if(filter_hl.equals("ANY"))
            filter_hl="%";
        if(filter_f.equals("ANY"))
            filter_f="%";

        qry=qry+" Where class like '"+filter_cl+"'";
        qry=qry+" and section like '"+filter_sec+"'";
        qry=qry+" and sex like '"+filter_g+"'";
        qry=qry+" and house like '"+filter_he+"'";
        qry=qry+" and hostel like '"+filter_hl+"'";
        qry=qry+" and floor like '"+filter_f+"'";

        if(admn.isSelected()==true)
            qry=qry+" ORDER by AdmnNo";

        if(nm.isSelected()==true)
            qry=qry+" ORDER by Name";

        if(ag.isSelected()==true)
            qry=qry+" ORDER by DOB";

        if(cl.isSelected()==true)
            qry=qry+" ORDER by class,section";
        
        if(hl.isSelected()==true)
            qry=qry+" ORDER by hostel,floor";

        if(he.isSelected()==true)
            qry=qry+" ORDER by house";

        if(ascRB.isSelected()==true)
            qry=qry+" asc";
            
        if(descRB.isSelected()==true)
            qry=qry+" desc";

        qry=qry+";";
        System.out.println(qry);
        //Data connectivity code
        DefaultTableModel dm=(DefaultTableModel) student.getModel();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();
            ResultSet rs=stmt.executeQuery(qry);

            int cnt=0;
            while(rs.next()){
                cnt++;
            }
            count.setText("Showing "+cnt+" Results");

            rs.beforeFirst();

            while(dm.getRowCount()>0)
                dm.removeRow(0);

           
            String n="",dob="",sc="",gd="",c_sc="",hos="",flo="",hos_flo="",hous="",admnNo="",c="";

            while(rs.next()){
                for(i=0;i<len;++i){
                    String field1=(String) fld[i];
                    if(field1.compareToIgnoreCase("AdmnNo")==0)
                        admnNo=rs.getString("AdmnNo");
                    else if(field1.compareToIgnoreCase("Name")==0)
                        n=rs.getString("Name");
                    else if(field1.compareToIgnoreCase("Class, Section")==0){
                        c=rs.getString("Class");
                        sc=rs.getString("Section");
                        c_sc=c+" "+sc;
                    }
                    else if(field1.compareToIgnoreCase("DOB")==0)
                        dob=rs.getString("DOB");
                    else if(field1.compareToIgnoreCase("sex")==0)
                        gd=rs.getString("sex");
                    else if(field1.compareToIgnoreCase("Hostel, Floor")==0){
                        hos=rs.getString("Hostel");
                        flo=rs.getString("Floor");
                        hos_flo=hos+" "+flo;
                    }
                    else if(field1.compareToIgnoreCase("House")==0)
                        hous=rs.getString("House");
                    
                }

                dm.addRow(new Object[]{admnNo,n,c_sc,dob,gd,hos_flo,hous});
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
             
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fetchTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admn;
    private javax.swing.JRadioButton ag;
    private javax.swing.JRadioButton ascRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cl;
    private javax.swing.JComboBox cls;
    private javax.swing.JLabel count;
    private javax.swing.JRadioButton descRB;
    private javax.swing.JList fieldList;
    private javax.swing.JComboBox floor;
    private javax.swing.JComboBox gender;
    private javax.swing.JRadioButton he;
    private javax.swing.JRadioButton hl;
    private javax.swing.JComboBox hostel;
    private javax.swing.JComboBox house;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton nm;
    private javax.swing.JComboBox sec;
    private javax.swing.JTable student;
    // End of variables declaration//GEN-END:variables

}
