/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * marks_insert.java
 *
 * Created on Oct 30, 2014, 5:13:28 PM
 */

package compproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Mukesh
 */
public class marks_insert extends javax.swing.JFrame {

    /** Creates new form marks_insert */
    public marks_insert() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clsCB = new javax.swing.JComboBox();
        semLbl = new javax.swing.JLabel();
        semCB = new javax.swing.JComboBox();
        entBtn = new javax.swing.JButton();
        subLbl = new javax.swing.JLabel();
        subCB = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mark = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secCB = new javax.swing.JComboBox();
        secLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(982, 591));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18));
        jLabel1.setText("Mark Slip");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 1, 14));
        jLabel2.setText("Class:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        clsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsCBActionPerformed(evt);
            }
        });
        getContentPane().add(clsCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 100, 20));

        semLbl.setFont(new java.awt.Font("Eras Demi ITC", 1, 14));
        semLbl.setText("Semester:");
        getContentPane().add(semLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, -1, -1));

        semCB.setFont(new java.awt.Font("Tahoma", 1, 11));
        semCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semCBActionPerformed(evt);
            }
        });
        getContentPane().add(semCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 90, 20));

        entBtn.setText("Enter");
        entBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entBtnActionPerformed(evt);
            }
        });
        getContentPane().add(entBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, -1));

        subLbl.setFont(new java.awt.Font("Eras Demi ITC", 1, 14));
        subLbl.setText("Subject:");
        getContentPane().add(subLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        subCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCBActionPerformed(evt);
            }
        });
        getContentPane().add(subCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 150, 20));

        mark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AdmnNo", "Name", "Para1 (out of)", "Para2 (out of)", "Para3 (out of)", "Para4 (out of)", "Para1(converted)", "Para2(converted)", "Para3(converted)", "Para4(converted)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mark);

        jLabel3.setFont(new java.awt.Font("Aharoni", 1, 16)); // NOI18N
        jLabel3.setText("Actual Marks Being Entered Out of ");

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 16)); // NOI18N
        jLabel4.setText("Actual Marks Being Entered Out of ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 950, 520));

        secCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secCBActionPerformed(evt);
            }
        });
        getContentPane().add(secCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 80, -1));

        secLbl.setFont(new java.awt.Font("Eras Demi ITC", 1, 14));
        secLbl.setText("Section:");
        getContentPane().add(secLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void entBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entBtnActionPerformed
    clsCB.setEnabled(false);
    secCB.setEnabled(false);
    subCB.setEnabled(false);
    semCB.setEnabled(false);

try{
    Class.forName("com.mysql.jdbc.Driver");
    Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
    Statement stmt=(Statement)con.createStatement();
    Statement stmt1=(Statement)con.createStatement();

    String sql1="Select * from exam_para where class="+cl+" and section='"+sc+"' and Subject='"+sub+"' and semester='"+sem+"';";
    ResultSet rs1=stmt.executeQuery(sql1);
    rs1.next();

    String P1=rs1.getString("Para1");
    int P1con=rs1.getInt("P1_outof");
    int P1cur=rs1.getInt("P1_entout");

    String P2=rs1.getString("Para2");
    int P2con=rs1.getInt("P2_outof");
    int P2cur=rs1.getInt("P2_entout");

    String P3=rs1.getString("Para3");
    int P3con=rs1.getInt("P3_outof");
    int P3cur=rs1.getInt("P3_entout");

    String P4=rs1.getString("Para4");
    int P4con=rs1.getInt("P4_outof");
    int P4cur=rs1.getInt("P4_entout");

    jPanel1.setVisible(true);
    
       String column_names[]= {"AdmnNo","Name",P1+" (out of "+P1cur+")",P2+" (out of "+P2cur+")",P3+" (out of "+P3cur+")",P4+" (out of "+P4cur+")",P1+" (out of "+P1con+")",P2+" (out of "+P2con+")",P3+" (out of "+P3con+")",P4+" (out of "+P4con+")"};
       DefaultTableModel table_model=new DefaultTableModel(column_names,10);
       mark.setModel(table_model);
    
    String sql2="Select AdmnNo,Name from student_master where Class="+cl+" and Section='"+sc+"'";
    ResultSet rs2=stmt1.executeQuery(sql2);

    while(rs2.next()){
                int ad=rs2.getInt("AdmnNo");
                String nm=rs2.getString("name");
    }
    
}
catch(Exception ex){
    JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
    jPanel1.setVisible(false);
}

    
}//GEN-LAST:event_entBtnActionPerformed
public String t_code;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        secCB.setVisible(false);
        secLbl.setVisible(false);
        semCB.setVisible(false);
        semLbl.setVisible(false);
        subCB.setVisible(false);
        subLbl.setVisible(false);
        
        jPanel1.setVisible(false);

        t_code=JOptionPane.showInputDialog(null,"Please enter teacher code");
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();

            String sql1="Select distinct(class) from exam_para natural join subjects where tch_code='"+t_code+"';";
            
            ResultSet rs1=stmt.executeQuery(sql1);
            while(rs1.next()){
                int c=rs1.getInt("class");
                clsCB.addItem(c);
            }

            con.close();
            stmt.close();
            rs1.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }
            
    }//GEN-LAST:event_formWindowOpened
public int cl;
public String sc;
    private void secCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secCBActionPerformed
try {
            JComboBox sec = (JComboBox) evt.getSource();
            sc=(String) sec.getSelectedItem();
            System.out.println(""+sc);

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();

            String sql="Select distinct(subject) from exam_para natural join subjects where (tch_code='"+t_code+"') and (class="+cl+") and (section='"+sc+"');";
            ResultSet rs = stmt.executeQuery(sql);

            int cnt_sub=subCB.getItemCount();
            System.out.println(cnt_sub);

            if(cnt_sub!=0){
                while(cnt_sub!=0){
                subCB.removeItemAt(0);
                cnt_sub=subCB.getItemCount();
                }
            }

            while(rs.next()){
                String s=rs.getString(1);
                subCB.addItem(s);
            }




            con.close();
            stmt.close();
            rs.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_secCBActionPerformed
public String sub,sem;
    private void clsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsCBActionPerformed
        secCB.setVisible(true);
        secLbl.setVisible(true);
        semCB.setVisible(true);
        semLbl.setVisible(true);
        subCB.setVisible(true);
        subLbl.setVisible(true);

        try {
            JComboBox cla = (JComboBox) evt.getSource();
            cl = (Integer) cla.getSelectedItem();
            System.out.println(""+cl);

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();

            String sql2="Select distinct(section) from subjects natural join exam_para where tch_code like '"+t_code+"' and class="+cl+";";
            ResultSet rs2 = stmt.executeQuery(sql2);

            int cnt_sec=secCB.getItemCount();
            if(cnt_sec!=0){
                while(cnt_sec!=0){
                secCB.removeItemAt(0);
                cnt_sec=secCB.getItemCount();
                }
            }

            while(rs2.next()){
                String s=rs2.getString("Section");
                secCB.addItem(s);
            }

            String sql3="select distinct(semester) from exam_para natural join subjects where class="+cl+" and section='"+sc+"' and Subject='"+sub+"';";
            ResultSet rs3=stmt.executeQuery(sql3);

            int cnt_sem=semCB.getItemCount();
            if(cnt_sem!=0){
                while(cnt_sem!=0){
                semCB.removeItemAt(0);
                cnt_sem=semCB.getItemCount();
                }
            }
            while(rs3.next()){
                String se=rs3.getString("Semester");
                semCB.addItem(se);
            }

            con.close();
            stmt.close();
            rs2.close();
            rs3.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_clsCBActionPerformed

    private void subCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCBActionPerformed
        sub=(String) subCB.getSelectedItem();
    }//GEN-LAST:event_subCBActionPerformed

    private void semCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semCBActionPerformed
        sem=(String) semCB.getSelectedItem();
    }//GEN-LAST:event_semCBActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new marks_insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox clsCB;
    private javax.swing.JButton entBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mark;
    private javax.swing.JComboBox secCB;
    private javax.swing.JLabel secLbl;
    private javax.swing.JComboBox semCB;
    private javax.swing.JLabel semLbl;
    private javax.swing.JComboBox subCB;
    private javax.swing.JLabel subLbl;
    // End of variables declaration//GEN-END:variables

}
