/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Search.java
 *
 * Created on Oct 14, 2014, 11:16:03 PM
 */

package compproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mukesh
 */
public class Search extends javax.swing.JFrame {

    /** Creates new form Search */
    public Search() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchCB = new javax.swing.JComboBox();
        nmad = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        admn = new javax.swing.JLabel();
        nm = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        cls = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        cls_tchr = new javax.swing.JLabel();
        house = new javax.swing.JLabel();
        hostel = new javax.swing.JLabel();
        RHM1 = new javax.swing.JLabel();
        and = new javax.swing.JLabel();
        RHM2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        floor = new javax.swing.JLabel();
        outcount = new javax.swing.JLabel();
        nowcount = new javax.swing.JLabel();
        slash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1076, 712));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        getContentPane().add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 650, -1, -1));

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 610, -1, -1));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 24));
        jLabel1.setText("Students Database");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Search by:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        searchCB.setFont(new java.awt.Font("Arial Black", 0, 12));
        searchCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admission Number", "Name" }));
        searchCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchCBItemStateChanged(evt);
            }
        });
        searchCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCBActionPerformed(evt);
            }
        });
        getContentPane().add(searchCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        nmad.setFont(new java.awt.Font("Bodoni MT", 1, 14));
        nmad.setText("Please enter");
        getContentPane().add(nmad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        searchTxt.setFont(new java.awt.Font("Cambria Math", 1, 18));
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        getContentPane().add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 200, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, -1, -1));

        jPanel1.setMaximumSize(new java.awt.Dimension(914, 563));
        jPanel1.setMinimumSize(new java.awt.Dimension(914, 563));

        jLabel3.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel3.setText("Admission Number:");

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel4.setText("Full Name:");

        jLabel5.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel5.setText("Gender:");

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel6.setText("Class:");

        jLabel7.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel7.setText("DOB:");

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel8.setText("Class Teacher:");

        jLabel9.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel9.setText("House:");

        jLabel10.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel10.setText("Hostel:");

        jLabel11.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel11.setText("Hostel Master (RHM):");

        admn.setFont(new java.awt.Font("Comic Sans MS", 1, 14));

        nm.setFont(new java.awt.Font("Comic Sans MS", 1, 14));

        gender.setFont(new java.awt.Font("Comic Sans MS", 1, 14));

        cls.setFont(new java.awt.Font("Comic Sans MS", 1, 14));

        dob.setFont(new java.awt.Font("Comic Sans MS", 1, 14));

        cls_tchr.setFont(new java.awt.Font("Comic Sans MS", 1, 14));

        house.setFont(new java.awt.Font("Comic Sans MS", 1, 14));

        hostel.setFont(new java.awt.Font("Comic Sans MS", 1, 14));

        RHM1.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        RHM1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        and.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        and.setText("and");

        RHM2.setFont(new java.awt.Font("Comic Sans MS", 1, 14));
        RHM2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel12.setFont(new java.awt.Font("Aharoni", 0, 15));
        jLabel12.setText("Floor:");

        floor.setFont(new java.awt.Font("Comic Sans MS", 1, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(48, 48, 48)
                        .addComponent(RHM1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(and))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cls_tchr, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(house, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(admn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nm, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(gender, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(cls, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(hostel, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(floor, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))))
                .addGap(26, 26, 26)
                .addComponent(RHM2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(admn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cls, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cls_tchr, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(house, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hostel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(RHM1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(and)
                    .addComponent(RHM2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        outcount.setFont(new java.awt.Font("Tahoma", 1, 14));
        outcount.setText("0");
        getContentPane().add(outcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 30, 40));

        nowcount.setFont(new java.awt.Font("Tahoma", 1, 14));
        nowcount.setText("0");
        getContentPane().add(nowcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 40));

        slash.setFont(new java.awt.Font("Tahoma", 1, 14));
        slash.setText("/");
        getContentPane().add(slash, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 10, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void adsearch(String ad){
    
            try {

             Class.forName("com.mysql.jdbc.Driver");
             Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
             Statement stmt=(Statement)con.createStatement();

             if(ad.contains("D")){
             int l=ad.length()-2;
             String adm=ad.substring(l);
             //System.out.println(l);
             admnno=Integer.parseInt(adm);
             }
             else{
             admnno=Integer.parseInt(ad);
             }

                 String sql1="Select *,DATE_FORMAT(DOB,'%D %M, %Y') as 'date',DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(dob-interval 1 day)), '%Y')+0 AS age from student_master where AdmnNo like "+admnno+";";
                 String sql2="select AdmnNo,t.name from student_master sm,classes,teachers t where (sm.class=Classes.class) and (sm.section=classes.section) and (classes.cls_tchr=t.code) and AdmnNo="+admnno+";";
                 String sql3="Select AdmnNo,(Select name from teachers where code like RHM1) 'RHM1',(Select name from teachers where code like RHM2) 'RHM2' from student_master sm,hostels h where (h.hostel=sm.hostel) and (h.floor=sm.floor) and AdmnNo="+admnno+";";

                 rs1=stmt.executeQuery(sql1);
                 rs1.next();
                 String a=rs1.getString("AdmnNo");
                 String name=rs1.getString("Name");
                 String sex=rs1.getString("sex");
                 int std=rs1.getInt("class");
                 String s=rs1.getString("section");
                 String DOB=rs1.getString("date");
                 int age=rs1.getInt("age");
                 String ho=rs1.getString("house");
                 String hos=rs1.getString("Hostel");
                 String f=rs1.getString("floor");

                 rs2=stmt.executeQuery(sql2);
                 rs2.next();
                 String ct=rs2.getString("name");



                 rs3=stmt.executeQuery(sql3);
                 rs3.next();
                 String r1=rs3.getString("RHM1");
                 String r2=rs3.getString("RHM2");

                 admn.setText(a);
                 nm.setText(name);
                 gender.setText(sex);
                 cls.setText(""+std+" "+s);
                 dob.setText(""+DOB+"  (Age "+age+")");
                 cls_tchr.setText(ct);
                 house.setText(ho);
                 hostel.setText(hos);
                 floor.setText(f);
                 RHM1.setText(r1);
                 RHM2.setText(r2);
            }

            catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
            }

                 }
public String fn,ln;
public String fname(String name){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();
            String sql="Select SUBSTRING_INDEX('"+name+"',' ',1);";
            ResultSet rs=stmt.executeQuery(sql);
            rs.next();
            fn=rs.getString(1);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }

            return fn;
    
}

public String lname(String name){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();
            String sql="Select SUBSTRING_INDEX('"+name+"',' ',-1);";
            ResultSet rs=stmt.executeQuery(sql);
            rs.next();
            ln=rs.getString(1);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }

            return ln;

}


    private void searchCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCBActionPerformed
        nmad.setVisible(true);
        searchTxt.setText("");
        searchTxt.setVisible(true);
        searchTxt.requestFocusInWindow();
        searchBtn.setVisible(true);
        
        String x=(String) searchCB.getSelectedItem();
        nmad.setText("Please enter the "+x+" :");
        
}//GEN-LAST:event_searchCBActionPerformed

    private void searchCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchCBItemStateChanged
       
}//GEN-LAST:event_searchCBItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        next.setEnabled(false);
        previous.setEnabled(false);
        
        nowcount.setVisible(false);
        outcount.setVisible(false);
        slash.setVisible(false);

        nmad.setVisible(false);
        searchTxt.setVisible(false);
        searchBtn.setVisible(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        searchBtn.doClick();
    }//GEN-LAST:event_searchTxtActionPerformed

public ResultSet rs1,rs2,rs3,rs4,rs5;
public int admnno,ncount,count;
//public String ad;
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        jPanel1.setVisible(true);
        
        String x=(String) searchCB.getSelectedItem();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt1=(Statement)con.createStatement();
              Statement stmt2=(Statement)con.createStatement();
             
             if(x.equals("Admission Number")){
                    previous.setEnabled(false);
                    next.setEnabled(false);
                    
                    nowcount.setVisible(false);
                    outcount.setVisible(false);
                    slash.setVisible(false);

                    String ad=searchTxt.getText();
                    adsearch(ad);
                     
             }
             else if(x.equals("Name")){
                 next.setEnabled(true);
                 previous.setEnabled(false);
                 
                 nowcount.setVisible(true);
                 outcount.setVisible(true);
                 slash.setVisible(true);

               String name=searchTxt.getText();

               String fnm=fname(name);
               String lnm=lname(name);
               String sql4="Select AdmnNo from student_master where (name like '%"+name+"%')||(name like '%"+fnm+"%')||(name like '%"+lnm+"%');";
               String sql5="Select count(AdmnNo) from student_master where (name like '%"+name+"%')||(name like '%"+fnm+"%')||(name like '%"+lnm+"%');";
               rs4=stmt1.executeQuery(sql4);
               rs5=stmt2.executeQuery(sql5);
               rs5.next();
               count=rs5.getInt("count(AdmnNo)");

               if(count==1)
                   next.setEnabled(false);
               
               rs4.next();
               String ad=rs4.getString("AdmnNo");
               adsearch(ad);

               ncount=1;
               outcount.setText(""+count);
               nowcount.setText(""+ncount);

             }
             
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
            jPanel1.setVisible(false);
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
       try {
            next.setEnabled(true);
            if(ncount==2){
                previous.setEnabled(false);
            }
            rs4.previous();
            String ad=rs4.getString("AdmnNo");
            adsearch(ad);
            ncount-=1;
            nowcount.setText(""+ncount);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
}//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        try {
            previous.setEnabled(true);
            if(count-ncount==1){
            next.setEnabled(false);
            }
            rs4.next();
            String ad=rs4.getString("AdmnNo");
            adsearch(ad);
            ncount+=1;
            nowcount.setText(""+ncount);
            
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
}//GEN-LAST:event_nextActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RHM1;
    private javax.swing.JLabel RHM2;
    private javax.swing.JLabel admn;
    private javax.swing.JLabel and;
    private javax.swing.JLabel cls;
    private javax.swing.JLabel cls_tchr;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel floor;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel hostel;
    private javax.swing.JLabel house;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JLabel nm;
    private javax.swing.JLabel nmad;
    private javax.swing.JLabel nowcount;
    private javax.swing.JLabel outcount;
    private javax.swing.JButton previous;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox searchCB;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel slash;
    // End of variables declaration//GEN-END:variables

}
