/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchTeachers.java
 *
 * Created on Oct 18, 2014, 5:49:26 PM
 */

package compproject;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Mukesh
 */
public class SearchTeachers extends javax.swing.JFrame {

    /** Creates new form SearchTeachers */
    public SearchTeachers() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchCB = new javax.swing.JComboBox();
        nmcd = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        code = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        qual = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dept = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        desig = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        resid = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        classes = new javax.swing.JTextArea();
        next = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        nowcount = new javax.swing.JLabel();
        slash = new javax.swing.JLabel();
        outcount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(861, 730));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18));
        jLabel1.setText("Teacher's Database");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Search by:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        searchCB.setFont(new java.awt.Font("Arial Black", 0, 12));
        searchCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Code", "Name" }));
        searchCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchCBItemStateChanged(evt);
            }
        });
        searchCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCBActionPerformed(evt);
            }
        });
        getContentPane().add(searchCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        nmcd.setFont(new java.awt.Font("Bodoni MT", 1, 14));
        nmcd.setText("Please enter");
        getContentPane().add(nmcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        searchTxt.setFont(new java.awt.Font("Cambria Math", 1, 18));
        searchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtActionPerformed(evt);
            }
        });
        getContentPane().add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 200, -1));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Aharoni", 0, 17));
        jLabel3.setText("Teacher Code:");

        code.setFont(new java.awt.Font("Aharoni", 1, 16));

        name.setFont(new java.awt.Font("Aharoni", 1, 16));

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 17));
        jLabel6.setText("Name:");

        gender.setFont(new java.awt.Font("Aharoni", 1, 16));

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 17));
        jLabel8.setText("Gender:");

        jLabel9.setFont(new java.awt.Font("Aharoni", 0, 17));
        jLabel9.setText("Qualification:");

        qual.setFont(new java.awt.Font("Aharoni", 1, 16));

        type.setFont(new java.awt.Font("Aharoni", 1, 16));

        jLabel12.setFont(new java.awt.Font("Aharoni", 0, 17));
        jLabel12.setText("Type:");

        jLabel13.setFont(new java.awt.Font("Aharoni", 0, 17));
        jLabel13.setText("Department:");

        dept.setFont(new java.awt.Font("Aharoni", 1, 16));

        jLabel15.setFont(new java.awt.Font("Aharoni", 0, 17));
        jLabel15.setText("Designation:");

        desig.setFont(new java.awt.Font("Aharoni", 1, 16));

        jLabel16.setFont(new java.awt.Font("Aharoni", 0, 17));
        jLabel16.setText("Residence:");

        resid.setFont(new java.awt.Font("Aharoni", 1, 16));

        jLabel17.setFont(new java.awt.Font("Aharoni", 0, 17));
        jLabel17.setText("Classes Taking:");

        classes.setColumns(20);
        classes.setEditable(false);
        classes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        classes.setRows(5);
        classes.setBorder(javax.swing.BorderFactory.createTitledBorder("Classes and Subjects"));
        classes.setOpaque(false);
        jScrollPane1.setViewportView(classes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(resid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(type, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(dept, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(gender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(qual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(code, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(desig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                        .addGap(135, 135, 135))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(qual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(desig, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(resid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(101, 101, 101))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 700, 590));

        next.setFont(new java.awt.Font("Tahoma", 1, 12));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, -1, -1));

        previous.setFont(new java.awt.Font("Tahoma", 1, 12));
        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        getContentPane().add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 680, -1, -1));

        nowcount.setFont(new java.awt.Font("Tahoma", 1, 14));
        nowcount.setText("0");
        getContentPane().add(nowcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 30, 40));

        slash.setFont(new java.awt.Font("Tahoma", 1, 14));
        slash.setText("/");
        getContentPane().add(slash, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 10, 40));

        outcount.setFont(new java.awt.Font("Tahoma", 1, 14));
        outcount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outcount.setText("0");
        getContentPane().add(outcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 30, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void cdsearch(String cd){

        try{
        Class.forName("com.mysql.jdbc.Driver");
             Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
             Statement stmt=(Statement)con.createStatement();

             String sql1="Select * from teachers where code='"+cd+"';";
             String sql2="Select * from hostels where (RHM1='"+cd+"') or (RHM2='"+cd+"')";
             String sql3="Select * from subjects where tch_code='"+cd+"';";

             rs1=stmt.executeQuery(sql1);
             rs1.next();

             String c=rs1.getString("Code");
             String nm=rs1.getString("name");
             String g=rs1.getString("Gender");
             String q=rs1.getString("Qualification");
             String t=rs1.getString("type");
             String dep=rs1.getString("Department");
             String des=rs1.getString("Designation");

             code.setText(c);
             name.setText(nm);

             if(g.equals("M"))
                 g="Male";
             else if(g.equals("F"))
                 g="Female";

             gender.setText(g);
             qual.setText(q);
             type.setText(t);
             dept.setText(dep);
             desig.setText(des);

             rs2=stmt.executeQuery(sql2);
             int cnt = 0;
             while(rs2.next()){
                 cnt++;
             }

             rs2.first();

             if(cnt==0)
                 resid.setText("Staff Quaters");

             else if(cnt==1){
                 String rh=rs2.getString("Hostel");
                 String rf=rs2.getString("Floor");
                 if(rf.equals("GF"))
                     rf="Ground Floor";
                 else if(rf.equals("FF"))
                     rf="First Floor";
                 
                 resid.setText(rh+" "+rf);
             }

             rs5=stmt.executeQuery(sql3);
             int no=0;
             classes.setText("");
             
             while(rs5.next()){
                 String cls=rs5.getString("class");
                 String sec=rs5.getString("Section");
                 String sub=rs5.getString("Subject");
                 no++;
                 if(no==1)
                 classes.append(cls+" "+sec+" - "+sub);
                 else
                   classes.append("\n"+cls+" "+sec+" - "+sub);
             }
             
    }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
    }
    private void searchCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchCBItemStateChanged

}//GEN-LAST:event_searchCBItemStateChanged
    public ResultSet rs1,rs2,rs3,rs4,rs5;
    private void searchCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCBActionPerformed
        nmcd.setVisible(true);
        searchTxt.setText("");
        searchTxt.setVisible(true);
        searchTxt.requestFocusInWindow();
        searchBtn.setVisible(true);

        String x=(String) searchCB.getSelectedItem();
        nmcd.setText("Please enter the "+x+" :");
    }//GEN-LAST:event_searchCBActionPerformed

    private void searchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtActionPerformed
        searchBtn.doClick();
}//GEN-LAST:event_searchTxtActionPerformed
public int count,ncount;
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        jPanel1.setVisible(true);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmtsb1=(Statement)con.createStatement();
            Statement stmtsb2=(Statement)con.createStatement();
              
        String x=(String) searchCB.getSelectedItem();
        
        String nacd=searchTxt.getText();

        if(x.equals("Code")){
            next.setEnabled(false);
            previous.setEnabled(false);

            nowcount.setVisible(false);
            outcount.setVisible(false);
            slash.setVisible(false);

            cdsearch(nacd);
        }

        else if(x.equals("Name")){
            next.setEnabled(true);
            previous.setEnabled(false);

            nowcount.setVisible(true);
            outcount.setVisible(true);
            slash.setVisible(true);

            String sqlsb1="Select code from teachers where name like '%"+nacd+"%';";
            String sqlsb2="Select count(code) from teachers where name like '%"+nacd+"%';";

            rs4=stmtsb1.executeQuery(sqlsb2);
            rs4.next();

            count=rs4.getInt("count(code)");
            if(count==1)
                   next.setEnabled(false);
            
            rs3=stmtsb2.executeQuery(sqlsb1);
            rs3.next();
            String cd=rs3.getString("code");
            cdsearch(cd);

            ncount=1;
            outcount.setText(""+count);
            nowcount.setText(""+ncount);
             
        }


        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
            jPanel1.setVisible(false);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPanel1.setVisible(false);
        nmcd.setVisible(false);
        searchTxt.setVisible(false);
        searchBtn.setVisible(false);

        next.setEnabled(false);
        previous.setEnabled(false);

        nowcount.setVisible(false);
        outcount.setVisible(false);
        slash.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
         try {
            previous.setEnabled(true);
            if(count-ncount==1){
            next.setEnabled(false);
            }
            rs3.next();
            String cd=rs3.getString("Code");
            cdsearch(cd);
            ncount+=1;
            nowcount.setText(""+ncount);


        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_nextActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        try {
            next.setEnabled(true);
            if(ncount==2){
                previous.setEnabled(false);
            }
            rs3.previous();
            String cd=rs3.getString("code");
            cdsearch(cd);
            ncount-=1;
            nowcount.setText(""+ncount);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_previousActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchTeachers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea classes;
    private javax.swing.JLabel code;
    private javax.swing.JLabel dept;
    private javax.swing.JLabel desig;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JButton next;
    private javax.swing.JLabel nmcd;
    private javax.swing.JLabel nowcount;
    private javax.swing.JLabel outcount;
    private javax.swing.JButton previous;
    private javax.swing.JLabel qual;
    private javax.swing.JLabel resid;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox searchCB;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel slash;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables

}
