/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * teach_fetch.java
 *
 * Created on Oct 22, 2014, 3:26:11 PM
 */

package compproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Mukesh
 */
public class teach_fetch extends javax.swing.JFrame {
    
    /** Creates new form teach_fetch */
    public teach_fetch() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldList = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        deptCB = new javax.swing.JComboBox();
        qualCB = new javax.swing.JComboBox();
        typeCB = new javax.swing.JComboBox();
        desigCB = new javax.swing.JComboBox();
        genderCB = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        clsCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        secCB = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        code = new javax.swing.JRadioButton();
        dept = new javax.swing.JRadioButton();
        name = new javax.swing.JRadioButton();
        type = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        ascRB = new javax.swing.JRadioButton();
        descRB = new javax.swing.JRadioButton();
        cls_take = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        teachers = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        count = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fields for Display"));
        jPanel1.setFont(new java.awt.Font("Aharoni", 1, 14));

        fieldList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Code", "Name", "Gender", "Qualification", "Type", "Department", "Designation" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(fieldList);

        jLabel7.setText("* Please select fields for Display");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jLabel1.setText("Department:");

        jLabel2.setText("Qualification:");

        jLabel3.setText("Type:");

        jLabel4.setText("Designation:");

        jLabel5.setText("Gender:");

        deptCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        qualCB.setEditable(true);
        qualCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY", "BSc", "MSc", "MSc (Physics)", "BA", "MA", "BA (Hindi)", "MA (Hindi)", "MA (English)", "MCA", "MPhil", "Diploma", "PhD", "BEd", "MEd", "BPEd", "MPEd" }));

        typeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        desigCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        genderCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        jLabel6.setText("Class taking:");

        clsCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        jLabel8.setText("* You may choose or type qualification for teacher eg. BA (Hindi)");

        secCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANY" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderCB, 0, 108, Short.MAX_VALUE)
                            .addComponent(typeCB, 0, 108, Short.MAX_VALUE)
                            .addComponent(deptCB, 0, 108, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clsCB, 0, 58, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secCB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(desigCB, 0, 130, Short.MAX_VALUE)
                                    .addComponent(qualCB, 0, 130, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deptCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(qualCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(typeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desigCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(clsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(secCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sorting"));

        buttonGroup1.add(code);
        code.setText("Code");

        buttonGroup1.add(dept);
        dept.setText("Department");

        buttonGroup1.add(name);
        name.setText("Name");

        buttonGroup1.add(type);
        type.setText("Type");

        buttonGroup2.add(ascRB);
        ascRB.setText("Ascending");

        buttonGroup2.add(descRB);
        descRB.setText("Descending");

        buttonGroup1.add(cls_take);
        cls_take.setText("Class taking");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(code)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(name)
                        .addGap(45, 45, 45)
                        .addComponent(type)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(dept)
                        .addGap(18, 18, 18)
                        .addComponent(cls_take)
                        .addContainerGap(62, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(ascRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(descRB)
                .addGap(33, 33, 33))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code)
                    .addComponent(type)
                    .addComponent(name))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cls_take)
                    .addComponent(dept))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ascRB)
                    .addComponent(descRB))
                .addContainerGap())
        );

        teachers.setBackground(new java.awt.Color(0, 10, 89));
        teachers.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        teachers.setForeground(new java.awt.Color(255, 255, 255));
        teachers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Gender", "Qualification", "Type", "Department", "Designation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teachers.setRowHeight(25);
        jScrollPane2.setViewportView(teachers);

        jButton1.setText("Fetch Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        count.setFont(new java.awt.Font("Tahoma", 1, 11));
        count.setText("Showing 0 Results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(360, 360, 360)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(690, 690, 690)
                            .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(165, 182, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jButton1)
                    .addGap(297, 297, 297)
                    .addComponent(count)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //assembling the query string
        Object fld1[]=fieldList.getSelectedValues();
        int len=fld1.length;

        if(len==0){
            fieldList.setSelectionInterval(0, 6);
            len=7;
        }
        System.out.println(""+len);

        Object fld[]=fieldList.getSelectedValues();

        String qry="SELECT distinct ";
        int i;
        String field=(String) fld[0];
        qry=qry+field;
        for(i=1;i<len;++i){
            String field1=(String) fld[i];
            qry=qry+","+field1;
        }

        
        String filter_dept,filter_qual,filter_type,filter_desig,filter_gender,filter_cls,filter_sec;

        filter_dept=(String) deptCB.getSelectedItem();
        filter_qual=(String) qualCB.getSelectedItem();
        filter_type=(String) typeCB.getSelectedItem();
        filter_desig=(String) desigCB.getSelectedItem();
        filter_gender=(String) genderCB.getSelectedItem();
        filter_cls=(String) clsCB.getSelectedItem();
        filter_sec=(String) secCB.getSelectedItem();

        if(filter_dept.equals("ANY"))
            filter_dept="%";
        if(filter_qual.equals("ANY"))
            filter_qual="%";
        if(filter_type.equals("ANY"))
            filter_type="%";
        if(filter_desig.equals("ANY"))
            filter_desig="%";
        if(filter_gender.equals("ANY"))
            filter_gender="%";
        if((filter_cls.equals("ANY"))&&(filter_sec.equals("ANY"))){
            qry=qry+" FROM teachers";
            qry=qry+" where Department like '"+filter_dept+"'";
        }
        else{
            qry=qry+" FROM teachers,subjects where (teachers.code=subjects.tch_code)";
            qry=qry+" and Department like '"+filter_dept+"'";
            qry=qry+" and Class like '"+filter_cls+"'";
            qry=qry+" and Section like '"+filter_sec+"'";
        }
           

        qry=qry+" and Qualification like '%"+filter_qual+"%'";
        qry=qry+" and type like '"+filter_type+"'";
        qry=qry+" and Designation like '"+filter_desig+"'";
        qry=qry+" and gender like '"+filter_gender+"'";

        if(code.isSelected()==true)
            qry=qry+" ORDER by code";

        else if(name.isSelected()==true)
            qry=qry+" ORDER by Name";

        else if(type.isSelected()==true)
            qry=qry+" ORDER by type";

        else if(dept.isSelected()==true)
            qry=qry+" ORDER by department";

        if(ascRB.isSelected()==true)
            qry=qry+" asc";

        if(descRB.isSelected()==true)
            qry=qry+" desc";
        

        qry=qry+";";
        System.out.println(qry);
        //Data connectivity code
        DefaultTableModel dm=(DefaultTableModel) teachers.getModel();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();
            ResultSet rs=stmt.executeQuery(qry);

            int cnt=0;
            while(rs.next()){
                cnt++;
            }
            count.setText("Showing "+cnt+" Results");

            rs.beforeFirst();

            while(dm.getRowCount()>0){
                dm.removeRow(0);
            }

            String cd="",nm="",gd="",qua="",typ="",dep="",desig="";

            while(rs.next()){
                for(i=0;i<len;++i){
                    String field1=(String) fld[i];
                    if(field1.compareToIgnoreCase("Code")==0)
                        cd=rs.getString("Code");
                    else if(field1.compareToIgnoreCase("Name")==0)
                        nm=rs.getString("Name");
                    else if(field1.compareToIgnoreCase("Gender")==0)
                        gd=rs.getString("Gender");
                    else if(field1.compareToIgnoreCase("Qualification")==0)
                        qua=rs.getString("Qualification");
                    else if(field1.compareToIgnoreCase("Type")==0)
                        typ=rs.getString("Type");
                    else if(field1.compareToIgnoreCase("Department")==0)
                        dep=rs.getString("Department");
                    else if(field1.compareToIgnoreCase("Designation")==0)
                        desig=rs.getString("Designation");

                }

                dm.addRow(new Object[]{cd,nm,gd,qua,typ,dep,desig});
            }

        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/skool","root","mysqlip");
            Statement stmt=(Statement)con.createStatement();

            String sql1="Select name from dept";
            ResultSet rs1=stmt.executeQuery(sql1);

            while(rs1.next()){
                String dn=rs1.getString("Name");
                deptCB.addItem(dn);
            }

            String sql2="Select distinct(type) from teachers";
            rs1=stmt.executeQuery(sql2);

            while(rs1.next()){
                String ty=rs1.getString("type");
                typeCB.addItem(ty);
            }

            String sql3="Select distinct(Designation) from teachers";
            rs1=stmt.executeQuery(sql3);

            while(rs1.next()){
                String des=rs1.getString("Designation");
                desigCB.addItem(des);
            }

            String sql4="Select distinct(gender) from teachers";
            rs1=stmt.executeQuery(sql4);

            while(rs1.next()){
                String gd=rs1.getString("gender");
                genderCB.addItem(gd);
            }

            String sql5="Select distinct(class) from classes";
            rs1=stmt.executeQuery(sql5);

            while(rs1.next()){
                String cl=rs1.getString("Class");
                clsCB.addItem(cl);
            }

            String sql6="Select distinct(section) from classes";
            rs1=stmt.executeQuery(sql6);

            while(rs1.next()){
                String sec=rs1.getString("Section");
                secCB.addItem(sec);
            }

            TableColumnModel tcm1 = teachers.getColumnModel();
             tcm1.getColumn(0).setMaxWidth(55);
             tcm1.getColumn(0).setMinWidth(55);
             tcm1.getColumn(1).setMaxWidth(230);
             tcm1.getColumn(1).setMinWidth(230);
             tcm1.getColumn(2).setMaxWidth(60);
             tcm1.getColumn(2).setMinWidth(60);
             tcm1.getColumn(3).setMaxWidth(300);
             tcm1.getColumn(3).setMinWidth(300);
             tcm1.getColumn(4).setMaxWidth(65);
             tcm1.getColumn(4).setMinWidth(65);
             tcm1.getColumn(5).setMaxWidth(155);
             tcm1.getColumn(5).setMinWidth(155);
             tcm1.getColumn(6).setMaxWidth(118);
             tcm1.getColumn(6).setMinWidth(118);

             DefaultTableCellRenderer centreRenderer = new DefaultTableCellRenderer();
             centreRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
             teachers.getColumn("Code").setCellRenderer( centreRenderer );
             teachers.getColumn("Name").setCellRenderer( centreRenderer );
             teachers.getColumn("Gender").setCellRenderer( centreRenderer );
             teachers.getColumn("Qualification").setCellRenderer( centreRenderer );
             teachers.getColumn("Type").setCellRenderer( centreRenderer );
             teachers.getColumn("Department").setCellRenderer( centreRenderer );
             teachers.getColumn("Designation").setCellRenderer( centreRenderer );

             
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teach_fetch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ascRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox clsCB;
    private javax.swing.JRadioButton cls_take;
    private javax.swing.JRadioButton code;
    private javax.swing.JLabel count;
    private javax.swing.JRadioButton dept;
    private javax.swing.JComboBox deptCB;
    private javax.swing.JRadioButton descRB;
    private javax.swing.JComboBox desigCB;
    private javax.swing.JList fieldList;
    private javax.swing.JComboBox genderCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton name;
    private javax.swing.JComboBox qualCB;
    private javax.swing.JComboBox secCB;
    private javax.swing.JTable teachers;
    private javax.swing.JRadioButton type;
    private javax.swing.JComboBox typeCB;
    // End of variables declaration//GEN-END:variables

}
